version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: D:/Python/notebook/recomm_prod/log/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: D:/Python/notebook/recomm_prod/log/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

#loggers:
#    recomm_prod:
#        level: INFO
#        handlers: [console, info_file_handler]
#        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler]